# Generated by Django 3.2.8 on 2021-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emailid',
            new_name='email',
        ),
    ]
